### ISSUE TITLE
Router wasn't available exclusively after waiting 15000ms

### ISSUE THREAD

**Issue by Doctoror** [4thline/cling#112]
Platform: Android 4.1.2
Cling: 2.0.1 with Jetty 8.1.8.v20121106

Steps to reproduce: start and stop upnp service multiple times until you get a wierd shutdown output

```
I/Router﹕ WiFi multicast lock released
I/Router﹕ WiFi lock released
I/UpnpServiceImpl﹕ <<< UPnP service shutdown completed
E/UpnpServiceImpl﹕ Router error on shutdown: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock
    org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock
            at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:497)
            at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
            at org.fourthline.cling.android.AndroidRouter.disable(AndroidRouter.java:108)
            at org.fourthline.cling.transport.RouterImpl.shutdown(RouterImpl.java:199)
            at org.fourthline.cling.android.AndroidRouter.shutdown(AndroidRouter.java:83)
            at org.fourthline.cling.UpnpServiceImpl.shutdownRouter(UpnpServiceImpl.java:162)
            at org.fourthline.cling.UpnpServiceImpl$1.run(UpnpServiceImpl.java:143)
I/UpnpServiceImpl﹕ <<< UPnP service shutdown completed // 2 shutdowns in a row, what gives?
```

Since I saw two shutdowns in a row, it seems like possible that you are doing something related to startup and shutdown in parallel?

Always reproduces in my project.
And after that, I get a constant spam of info warnings in LogCat.

```
I/pnpServiceConfiguration﹕ Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
I/pnpServiceConfiguration﹕ Thread pool rejected execution of class org.fourthline.cling.protocol.async.ReceivingSearch
```

Start up and shutdown still seems to work according to logs after that incident, but the spamming of `Thread pool rejected execution` never stops.

**Comment by levuphuong** [comment]
Hi 
i had same problem because i miss super.ondestroy() 
Add it then it normally work :)

**Comment by ened** [comment]
@levuphuong where exactly?

**Comment by levuphuong** [comment]
Move super.ondestroy() to below removeListener() and unbindService().
Hi @ened 
I want public my app in google play
Can i do this?
Need to add cling link description in Google play or do what to get license  ?

Thanks

**Comment by ened** [comment]
@levuphuong sure, you can publish any App using Cling as it is open source. Only if you make changes to Cling itself, then you need to publish those changes as well. 

Regarding the "super.onDestroy()" to below "removeListener()", would you please share some demo project?

**Comment by levuphuong** [comment]
public void onDestroy() {
		//if super.onDestroy(); in here cause problem
		if (upnpService != null) {
			upnpService.getRegistry().removeListener(registryListener);
		}

		getActivity().getApplicationContext().unbindService(
				serviceServerConnection);
		getActivity().getApplicationContext().unbindService(serviceConnection);
               super.onDestroy();
}

This is my case, i don't know what happen with Doctoror.

Regard,

**Comment by Doctoror** [comment]
Hi.
Due to heavy Jetty server, lots of tools I don't use and other issues I don't use Cling anymore. Instead I made my own lightweight UPnP client implementation so there will be no more updates from me regarding the issue.
Thanks.

**Comment by Aguaimama** [comment]
I had the same problems,when upnpservice shutdown ,the router throw exceptin org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock.then the upnpservice can not correctly start again

**Comment by auras** [comment]
Wouldn't it be better to write the messages in a queue instead of trying to send them immediately?

**Comment by auras** [comment]
See possible answer: https://github.com/4thline/cling/issues/170#issuecomment-230787478

**Comment by panda912** [comment]
I got the similar problem.

`java.lang.RuntimeException: Fatal error while executing protocol 'SendingSearch': org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:499)
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
	at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:305)
	at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	... 3 more
org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:499)
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
	at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:305)
	at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)`
