### ISSUE TITLE
App Crash when position info get Track values is null

### ISSUE THREAD

**Issue by aravindasthme** [4thline/cling#121]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long org.teleal.cling.model.types.UnsignedIntegerFourBytes.getValue()' on a null object reference
            at org.teleal.cling.support.model.PositionInfo.<init>(PositionInfo.java:44)
            at org.teleal.cling.support.avtransport.callback.GetPositionInfo.success(GetPositionInfo.java:46)
            at org.teleal.cling.controlpoint.ActionCallback.run(ActionCallback.java:156)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by ened** [comment]
Please migrate to Cling2.0.

**Comment by aravindasthme** [comment]
if i update to cling 2.it wont happen?

**Comment by ened** [comment]
Cling 1.x is quite old and completely unsupported by now, your chances are much better with 2.x.

**Comment by aravindasthme** [comment]
Thanks I have updated 2,it seems fine

**Comment by ened** [comment]
Close the ticket please.
