### ISSUE TITLE
Apps using Cling are failing to start on android lower than 5.0

### ISSUE THREAD

**Issue by mariusleu** [4thline/cling#155]
I have an android app using the Cling library according to the documentation.
On Android 5.0 or greater, it works very well.
On lower versions of android, the app compiles but fails to start.

````
java.lang.VerifyError: org/fourthline/cling/UpnpServiceImpl
            at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2931)
            at android.app.ActivityThread.access$1600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5789)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:843)
            at dalvik.system.NativeStart.main(Native Method)
````

I believe Cling is making some "system" calls that are not compatible with lower versions of android, even though according to the documentation the minimum api version is 15.

**Comment by christianbauer** [comment]
I don't know what that exception means. Other people also don't know but there are many guessing: http://stackoverflow.com/questions/668788/android-java-lang-verifyerror

**Comment by ened** [comment]
Please ask on Stackoverflow. Please ensure to run a fresh & clean build and turn of Android Studios Instant Run, if you were using it.

**Comment by mariusleu** [comment]
Solved this issue by making my app a MultiDexApplication.

http://developer.android.com/tools/building/multidex.html
