### ISSUE TITLE
java.lang.ExceptionInInitializerError 

### ISSUE THREAD

**Issue by JulyDev** [4thline/cling#188]
Hi:

config:
    compile 'org.fourthline.cling:cling-core:2.1.1'
    compile 'org.fourthline.cling:cling-support:2.1.1'
    compile 'org.eclipse.jetty:jetty-server:8.2.0.v20160908'
    compile 'org.eclipse.jetty:jetty-servlet:8.2.0.v20160908'
    compile 'org.eclipse.jetty:jetty-client:8.2.0.v20160908'
    compile 'org.slf4j:slf4j-jdk14:1.7.14'

 When I used cling sdk on xiaomi PAD, it crashed:
java.lang.ExceptionInInitializerError
 at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:711)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
at org.eclipse.jetty.server.Server.doStart(Server.java:282)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.startIfNotRunning(JettyServletContainer.java:141)
at org.fourthline.cling.transport.impl.AsyncServletStreamServerImpl.run(AsyncServletStreamServerImpl.java:92)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
 at org.eclipse.jetty.util.StringUtil.asciiToLowerCase(StringUtil.java:106)
at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:138)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:711) 
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) 
 at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) 
 at org.eclipse.jetty.server.Server.doStart(Server.java:282) 
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) 
 at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.startIfNotRunning(JettyServletContainer.java:141) 
at org.fourthline.cling.transport.impl.AsyncServletStreamServerImpl.run(AsyncServletStreamServerImpl.java:92) 
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841) 

![apad_info](https://cloud.githubusercontent.com/assets/19604766/23687688/b473fea2-03ea-11e7-8fc7-2979790dd058.png)

![qq 20170307183257](https://cloud.githubusercontent.com/assets/19604766/23652930/9ca8e72c-0365-11e7-995e-84fef94e70dc.png)

Thanks

**Comment by JulyDev** [comment]
Finally,I solved this problem by fixing that NullPointerException in StringUtil.java
see  https://github.com/eclipse/jetty.project/issues/1393
http://stackoverflow.com/questions/31769747/how-to-checkout-jetty-util-jetty-util-8-1-17-v20150415-from-git
