### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: 

### ISSUE THREAD

**Issue by JulyDev** [4thline/cling#193]
Hi:
   Sometimes , I get a lot of OOM on some android phones:
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Thread.java)
	at java.lang.Thread.start(Thread.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1338)
	at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java)
	                                             unlock(RouterImpl.java)
	                                             getLockTimeoutMillis(RouterImpl.java)
	at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java)
	at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java)
	at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java)
	at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java)
	at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3027)
	at android.app.ActivityThread.access$1800(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5682)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by inan1993** [comment]
Essential repeated thread failures
You should follow the general advice offered [here](https://stackoverflow.com/questions/35701501/throwing-outofmemoryerror-pthread-create-1040kb-stack-failed-try-again-when)

**Comment by nonelse** [comment]
@inan1993, thanks for the link, but it seems to apply to network requests, while this case is tied to the app lifecycle.

We already saw similar reports and profiled our SDK with Android Studio profiler and with adb memory dumps and unfortunately could not find anything out of the ordinary.

Our suspicion is that the SDK is tripping over the limit increased elsewhere on the app, or even system since it seems to occur more in a small range of devices with specific OS versions.

We will continue to look into this, but if you have any insights that could help us track it, we would appreciate it.
