### ISSUE TITLE
There is an exception in Android 7.1.1

### ISSUE THREAD

**Issue by gongjie** [4thline/cling#220]
> Failed injecting hostName to work around Android InetAddress DNS bug: /192.168.23.123
java.lang.NoSuchFieldException: No field hostName in class Ljava/net/InetAddress; (declaration of 'java.net.InetAddress' appears in /system/framework/core-oj.jar)
at java.lang.Class.getDeclaredField(Native Method)
at org.fourthline.cling.android.AndroidNetworkAddressFactory.isUsableAddress(AndroidNetworkAddressFactory.java:57)
at org.fourthline.cling.transport.impl.NetworkAddressFactoryImpl.discoverBindAddresses(NetworkAddressFactoryImpl.java:404)
at org.fourthline.cling.transport.impl.NetworkAddressFactoryImpl.<init>(NetworkAddressFactoryImpl.java:91)
at org.fourthline.cling.android.AndroidNetworkAddressFactory.<init>(AndroidNetworkAddressFactory.java:0)
at org.fourthline.cling.android.AndroidUpnpServiceConfiguration.createNetworkAddressFactory(AndroidUpnpServiceConfiguration.java:77)
at org.fourthline.cling.DefaultUpnpServiceConfiguration.createNetworkAddressFactory(DefaultUpnpServiceConfiguration.java:257)
at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:129)
at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:88)
at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)
at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:0)
at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3191)
at android.app.ActivityThread.-wrap5(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6126)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Muazzim-android** [comment]
Same here

**Comment by wuxiantao1115** [comment]
请问这个问题有解决吗？

**Comment by shrutigoyal7032** [comment]
I am facing same issue.
