### ISSUE TITLE
Fatal error while executing protocol 'ReceivingSearch

### ISSUE THREAD

**Issue by 415848878** [4thline/cling#242]
java.lang.RuntimeException: Fatal error while executing protocol 'ReceivingSearch': org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
	at org.fourthline.cling.protocol.ReceivingAsync.run(ReceivingAsync.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:499)
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
	at org.fourthline.cling.transport.RouterImpl.getActiveStreamServers(RouterImpl.java:218)
	at org.fourthline.cling.protocol.async.ReceivingSearch.execute(ReceivingSearch.java:98)
	at org.fourthline.cling.protocol.ReceivingAsync.run(ReceivingAsync.java:71)
	... 3 more
org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:499)
	at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
	at org.fourthline.cling.transport.RouterImpl.getActiveStreamServers(RouterImpl.java:218)
	at org.fourthline.cling.protocol.async.ReceivingSearch.execute(ReceivingSearch.java:98)
	at org.fourthline.cling.protocol.ReceivingAsync.run(ReceivingAsync.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by chaocharleswang** [comment]
Hi, Do you have any updates about this error? Thank you!
